#include "Transpiler.h"

namespace GameLang {

static void collectExpr(const Expr* expr, std::set<std::string>& members, std::set<std::string>& calls) {
    if (!expr) return;
    if (auto bin = dynamic_cast<const BinaryExpr*>(expr)) {
        collectExpr(bin->left.get(), members, calls);
        collectExpr(bin->right.get(), members, calls);
    } else if (auto un = dynamic_cast<const UnaryExpr*>(expr)) {
        collectExpr(un->right.get(), members, calls);
    } else if (auto asgn = dynamic_cast<const AssignExpr*>(expr)) {
        collectExpr(asgn->value.get(), members, calls);
    } else if (auto mem = dynamic_cast<const MemberAccessExpr*>(expr)) {
        members.insert(mem->member);
        collectExpr(mem->object.get(), members, calls);
    } else if (auto memAsgn = dynamic_cast<const MemberAssignExpr*>(expr)) {
        members.insert(memAsgn->member);
        collectExpr(memAsgn->object.get(), members, calls);
        collectExpr(memAsgn->value.get(), members, calls);
    } else if (auto call = dynamic_cast<const CallExpr*>(expr)) {
        calls.insert(call->callee);
        for (const auto& arg : call->arguments) {
            collectExpr(arg.get(), members, calls);
        }
    }
}

static void collectStmt(const Stmt* stmt, std::set<std::string>& members, std::set<std::string>& calls) {
    if (!stmt) return;
    if (auto exprStmt = dynamic_cast<const ExprStmt*>(stmt)) {
        collectExpr(exprStmt->expr.get(), members, calls);
    } else if (auto varDecl = dynamic_cast<const VarDeclStmt*>(stmt)) {
        if (varDecl->initializer) collectExpr(varDecl->initializer.get(), members, calls);
    } else if (auto ifStmt = dynamic_cast<const IfStmt*>(stmt)) {
        collectExpr(ifStmt->condition.get(), members, calls);
        collectStmt(ifStmt->thenBranch.get(), members, calls);
        collectStmt(ifStmt->elseBranch.get(), members, calls);
    } else if (auto whileStmt = dynamic_cast<const WhileStmt*>(stmt)) {
        collectExpr(whileStmt->condition.get(), members, calls);
        collectStmt(whileStmt->body.get(), members, calls);
    } else if (auto blockStmt = dynamic_cast<const BlockStmt*>(stmt)) {
        for (const auto& s : blockStmt->statements) collectStmt(s.get(), members, calls);
    } else if (auto returnStmt = dynamic_cast<const ReturnStmt*>(stmt)) {
        if (returnStmt->value) collectExpr(returnStmt->value.get(), members, calls);
    } else if (auto destroyStmt = dynamic_cast<const DestroyStmt*>(stmt)) {
        collectExpr(destroyStmt->target.get(), members, calls);
    }
}

void Transpiler::emitIndent(std::ostringstream& ss, int indent) {
    for (int i = 0; i < indent; ++i) ss << "    ";
}

std::string Transpiler::transpileToCpp(const Program& program) {
    std::ostringstream ss;

    std::set<std::string> accessedMembers;
    std::set<std::string> calledFunctions;
    for (const auto& g : program.globals) {
        if (g->initializer) collectExpr(g->initializer.get(), accessedMembers, calledFunctions);
    }
    for (const auto& fn : program.functions) {
        if (fn->body) collectStmt(fn->body.get(), accessedMembers, calledFunctions);
    }
    if (program.initBlock) collectStmt(program.initBlock.get(), accessedMembers, calledFunctions);
    if (program.updateBlock) collectStmt(program.updateBlock.get(), accessedMembers, calledFunctions);
    if (program.renderBlock) collectStmt(program.renderBlock.get(), accessedMembers, calledFunctions);
    for (const auto& ch : program.collisionHandlers) {
        if (ch->body) collectStmt(ch->body.get(), accessedMembers, calledFunctions);
    }

    ss << "// Generated by GameForge C++ Game Compiler\n";
    ss << "#include <iostream>\n";
    ss << "#include <vector>\n";
    ss << "#include <string>\n";
    ss << "#include <unordered_map>\n";
    ss << "#include <memory>\n";
    ss << "#include <chrono>\n";
    ss << "#include <thread>\n";
    ss << "#include <cmath>\n";
    ss << "#include <random>\n";
    ss << "#include <algorithm>\n";
    ss << "#ifdef _WIN32\n";
    ss << "#define WIN32_LEAN_AND_MEAN\n";
    ss << "#include <windows.h>\n";
    ss << "#include <conio.h>\n";
    ss << "#endif\n\n";

    // Embed standalone mini engine
    ss << R"RAW(
namespace GameRuntime {
    enum class Color { Default, Black, Red, Green, Yellow, Blue, Magenta, Cyan, White };

    inline std::string colorToAnsi(Color c) {
        switch (c) {
            case Color::Black:   return "\033[30m";
            case Color::Red:     return "\033[91m";
            case Color::Green:   return "\033[92m";
            case Color::Yellow:  return "\033[93m";
            case Color::Blue:    return "\033[94m";
            case Color::Magenta: return "\033[95m";
            case Color::Cyan:    return "\033[96m";
            case Color::White:   return "\033[97m";
            default:             return "\033[0m";
        }
    }

    inline Color parseColor(const std::string& name) {
        std::string s = name;
        std::transform(s.begin(), s.end(), s.begin(), ::tolower);
        if (s == "red") return Color::Red;
        if (s == "green") return Color::Green;
        if (s == "yellow") return Color::Yellow;
        if (s == "blue") return Color::Blue;
        if (s == "magenta") return Color::Magenta;
        if (s == "cyan") return Color::Cyan;
        if (s == "white") return Color::White;
        if (s == "black") return Color::Black;
        return Color::Default;
    }

    struct Pixel { char ch = ' '; Color color = Color::White; };
    struct Tile { char ch = ' '; Color color = Color::White; bool solid = false; };
)RAW";

    ss << "    struct BaseEntity {\n";
    ss << "        uint32_t id = 0;\n";
    ss << "        std::string type;\n";
    ss << "        bool active = true;\n";
    ss << "        double x = 0;\n";
    ss << "        double y = 0;\n";
    ss << "        double vx = 0;\n";
    ss << "        double vy = 0;\n";
    ss << "        double hp = 0;\n";
    ss << "        double alive = 1;\n";
    ss << "        std::string symbol = \"?\";\n";
    ss << "        std::string color = \"white\";\n";
    for (const auto& mem : accessedMembers) {
        if (mem != "x" && mem != "y" && mem != "vx" && mem != "vy" &&
            mem != "hp" && mem != "alive" && mem != "symbol" && mem != "color" &&
            mem != "id" && mem != "type" && mem != "active") {
            ss << "        double " << mem << " = 0.0;\n";
        }
    }
    ss << "        virtual ~BaseEntity() = default;\n";
    ss << "    };\n";

    ss << R"RAW(
    struct Value {
        double num = 0.0;
        std::string str;
        std::shared_ptr<BaseEntity> entity = nullptr;

        Value() = default;
        Value(double n) : num(n) {}
        Value(int n) : num(static_cast<double>(n)) {}
        Value(const char* s) : str(s) {}
        Value(std::string s) : str(std::move(s)) {}
        template<typename T>
        Value(std::shared_ptr<T> e) : entity(std::static_pointer_cast<BaseEntity>(e)) {}

        static BaseEntity* getSafeDummy() {
            static BaseEntity dummy;
            dummy.active = false;
            dummy.x = 0; dummy.y = 0; dummy.vx = 0; dummy.vy = 0;
            return &dummy;
        }
        BaseEntity* operator->() const { return entity ? entity.get() : getSafeDummy(); }
        explicit operator double() const { return num; }
        explicit operator int() const { return static_cast<int>(num); }
        operator bool() const { return entity != nullptr || num != 0.0; }

        Value& operator=(double n) { num = n; entity = nullptr; return *this; }
        Value& operator=(int n) { num = static_cast<double>(n); entity = nullptr; return *this; }
        Value& operator=(const std::string& s) { str = s; return *this; }
        template<typename T>
        Value& operator=(std::shared_ptr<T> e) { entity = std::static_pointer_cast<BaseEntity>(e); return *this; }

        Value operator+(const Value& o) const { return Value(num + o.num); }
        Value operator-(const Value& o) const { return Value(num - o.num); }
        Value operator*(const Value& o) const { return Value(num * o.num); }
        Value operator/(const Value& o) const { return Value(o.num != 0 ? num / o.num : 0); }
        bool operator==(const Value& o) const { return num == o.num && entity == o.entity; }
        bool operator!=(const Value& o) const { return !(*this == o); }
        bool operator<(const Value& o) const { return num < o.num; }
        bool operator<=(const Value& o) const { return num <= o.num; }
        bool operator>(const Value& o) const { return num > o.num; }
        bool operator>=(const Value& o) const { return num >= o.num; }

        Value operator+(double d) const { return Value(num + d); }
        Value operator-(double d) const { return Value(num - d); }
        Value operator*(double d) const { return Value(num * d); }
        Value operator/(double d) const { return Value(d != 0 ? num / d : 0); }
        Value operator+(int i) const { return Value(num + i); }
        Value operator-(int i) const { return Value(num - i); }
        Value operator*(int i) const { return Value(num * i); }
        Value operator/(int i) const { return Value(i != 0 ? num / i : 0); }

        bool operator<(double d) const { return num < d; }
        bool operator<=(double d) const { return num <= d; }
        bool operator>(double d) const { return num > d; }
        bool operator>=(double d) const { return num >= d; }
        bool operator==(double d) const { return num == d; }
        bool operator!=(double d) const { return num != d; }

        bool operator<(int i) const { return num < i; }
        bool operator<=(int i) const { return num <= i; }
        bool operator>(int i) const { return num > i; }
        bool operator>=(int i) const { return num >= i; }
        bool operator==(int i) const { return num == i; }
        bool operator!=(int i) const { return num != i; }

        friend Value operator+(double d, const Value& v) { return Value(d + v.num); }
        friend Value operator-(double d, const Value& v) { return Value(d - v.num); }
        friend Value operator*(double d, const Value& v) { return Value(d * v.num); }
        friend Value operator/(double d, const Value& v) { return Value(v.num != 0 ? d / v.num : 0); }
        friend Value operator+(int i, const Value& v) { return Value(i + v.num); }
        friend Value operator-(int i, const Value& v) { return Value(i - v.num); }
        friend Value operator*(int i, const Value& v) { return Value(i * v.num); }
        friend Value operator/(int i, const Value& v) { return Value(v.num != 0 ? i / v.num : 0); }

        friend bool operator<(double d, const Value& v) { return d < v.num; }
        friend bool operator<=(double d, const Value& v) { return d <= v.num; }
        friend bool operator>(double d, const Value& v) { return d > v.num; }
        friend bool operator>=(double d, const Value& v) { return d >= v.num; }
        friend bool operator==(double d, const Value& v) { return d == v.num; }
        friend bool operator!=(double d, const Value& v) { return d != v.num; }

        friend bool operator<(int i, const Value& v) { return i < v.num; }
        friend bool operator<=(int i, const Value& v) { return i <= v.num; }
        friend bool operator>(int i, const Value& v) { return i > v.num; }
        friend bool operator>=(int i, const Value& v) { return i >= v.num; }
        friend bool operator==(int i, const Value& v) { return i == v.num; }
        friend bool operator!=(int i, const Value& v) { return i != v.num; }
    };

    class Engine {
    public:
        int width;
        int height;
        int targetFps;
        std::string title;
        bool exitRequested = false;
        std::vector<Pixel> backBuffer;
        int mapWidth = 80;
        int mapHeight = 25;
        std::vector<Tile> tiles;
        int cameraX = 0;
        int cameraY = 0;
        std::string currentMessage;
        Color messageColor = Color::Yellow;
        uint32_t nextId = 1;
        std::unordered_map<std::string, bool> keysDown;
        std::unordered_map<std::string, bool> keysPressed;
        std::vector<std::shared_ptr<BaseEntity>> entities;
        std::chrono::steady_clock::time_point lastFrameTime;
        #ifdef _WIN32
        HANDLE hConsole = nullptr;
        DWORD originalMode = 0;
        #endif

        Engine(int w, int h, int fps, std::string t) : width(w), height(h), targetFps(fps), title(t) {
            backBuffer.resize(w * h, Pixel{' ', Color::Default});
            mapWidth = w;
            mapHeight = h;
            tiles.resize(w * h, Tile{' ', Color::Default, false});
            lastFrameTime = std::chrono::steady_clock::now();
        }

        void setMapSize(int w, int h) {
            mapWidth = w;
            mapHeight = h;
            tiles.assign(w * h, Tile{' ', Color::Default, false});
        }

        void setTile(int x, int y, char ch, Color col, bool solid) {
            if (x >= 0 && x < mapWidth && y >= 0 && y < mapHeight) {
                tiles[y * mapWidth + x] = Tile{ch, col, solid};
            }
        }

        bool isTileSolid(int x, int y) const {
            if (x < 0 || x >= mapWidth || y < 0 || y >= mapHeight) return true;
            return tiles[y * mapWidth + x].solid;
        }

        char getTileChar(int x, int y) const {
            if (x < 0 || x >= mapWidth || y < 0 || y >= mapHeight) return ' ';
            return tiles[y * mapWidth + x].ch;
        }

        void fillMapBox(int x, int y, int w, int h, char ch, Color col, bool solid) {
            for (int cy = y; cy < y + h; ++cy) {
                for (int cx = x; cx < x + w; ++cx) {
                    if (cy == y || cy == y + h - 1 || cx == x || cx == x + w - 1) {
                        setTile(cx, cy, ch, col, solid);
                    }
                }
            }
        }

        void setMapRow(int x, int y, const std::string& row, Color col, bool solid) {
            for (size_t i = 0; i < row.size(); ++i) {
                setTile(x + (int)i, y, row[i], col, solid);
            }
        }

        void setCamera(int cx, int cy) {
            cameraX = cx;
            cameraY = cy;
        }

        void setMessage(const std::string& msg, Color col = Color::Yellow) {
            currentMessage = msg;
            messageColor = col;
        }

        void initTerminal() {
            #ifdef _WIN32
            hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
            if (hConsole != INVALID_HANDLE_VALUE) {
                GetConsoleMode(hConsole, &originalMode);
                SetConsoleMode(hConsole, originalMode | ENABLE_VIRTUAL_TERMINAL_PROCESSING);
                CONSOLE_CURSOR_INFO ci;
                GetConsoleCursorInfo(hConsole, &ci);
                ci.bVisible = FALSE;
                SetConsoleCursorInfo(hConsole, &ci);
            }
            #endif
            std::cout << "\033]0;" << title << "\007\033[2J\033[H" << std::flush;
        }

        void resetTerminal() {
            #ifdef _WIN32
            if (hConsole != INVALID_HANDLE_VALUE) {
                SetConsoleMode(hConsole, originalMode);
                CONSOLE_CURSOR_INFO ci;
                GetConsoleCursorInfo(hConsole, &ci);
                ci.bVisible = TRUE;
                SetConsoleCursorInfo(hConsole, &ci);
            }
            #endif
            std::cout << "\033[0m\033[?25h\n" << std::flush;
        }

        void clear() {
            for (auto& p : backBuffer) p = Pixel{' ', Color::Default};
        }

        void setPixel(int x, int y, char ch, Color col) {
            if (x >= 0 && x < width && y >= 0 && y < height) {
                backBuffer[y * width + x] = Pixel{ch, col};
            }
        }

        void drawText(int x, int y, const std::string& text, Color col) {
            for (size_t i = 0; i < text.size(); ++i) setPixel(x + (int)i, y, text[i], col);
        }

        void drawBox(int x, int y, int w, int h, Color col) {
            for (int i = 0; i < w; ++i) { setPixel(x + i, y, '-', col); setPixel(x + i, y + h - 1, '-', col); }
            for (int i = 0; i < h; ++i) { setPixel(x, y + i, '|', col); setPixel(x + w - 1, y + i, '|', col); }
            setPixel(x, y, '+', col); setPixel(x + w - 1, y, '+', col);
            setPixel(x, y + h - 1, '+', col); setPixel(x + w - 1, y + h - 1, '+', col);
        }

        void present() {
            std::string frame = "\033[H";
            Color cur = Color::Default;
            for (int y = 0; y < height; ++y) {
                for (int x = 0; x < width; ++x) {
                    const auto& p = backBuffer[y * width + x];
                    if (p.color != cur) { frame += colorToAnsi(p.color); cur = p.color; }
                    frame += p.ch;
                }
                frame += "\n";
            }
            if (cur != Color::Default) frame += "\033[0m";
            std::cout << frame << std::flush;
        }

        void pollInput() {
            keysPressed.clear();
            #ifdef _WIN32
            while (_kbhit()) {
                int ch = _getch();
                std::string k;
                if (ch == 224 || ch == 0) {
                    int ext = _getch();
                    if (ext == 72) k = "UP";
                    else if (ext == 80) k = "DOWN";
                    else if (ext == 75) k = "LEFT";
                    else if (ext == 77) k = "RIGHT";
                } else if (ch == 27 || ch == 'q' || ch == 'Q') {
                    exitRequested = true;
                } else if (ch == 32) {
                    k = "SPACE";
                } else {
                    k = std::string(1, (char)toupper(ch));
                }
                if (!k.empty()) { keysDown[k] = true; keysPressed[k] = true; }
            }
            auto checkAsync = [&](int vk, const std::string& name) {
                if (GetAsyncKeyState(vk) & 0x8000) keysDown[name] = true;
                else keysDown[name] = false;
            };
            checkAsync(VK_LEFT, "LEFT"); checkAsync(VK_RIGHT, "RIGHT");
            checkAsync(VK_UP, "UP"); checkAsync(VK_DOWN, "DOWN");
            checkAsync(VK_SPACE, "SPACE");
            if (keysDown["A"]) keysDown["LEFT"] = true;
            if (keysDown["D"]) keysDown["RIGHT"] = true;
            if (keysDown["W"]) keysDown["UP"] = true;
            if (keysDown["S"]) keysDown["DOWN"] = true;
            #endif
        }

        bool isKeyDown(const std::string& key) const {
            auto it = keysDown.find(key); return it != keysDown.end() && it->second;
        }

        bool isKeyPressed(const std::string& key) const {
            auto it = keysPressed.find(key); return it != keysPressed.end() && it->second;
        }

        void playBeep(int freq, int dur) {
            #ifdef _WIN32
            if (freq > 0 && dur > 0) Beep(freq, std::min(dur, 40));
            #endif
        }

        int getRandomInt(int minVal, int maxVal) {
            static std::mt19937 rng(42);
            if (minVal > maxVal) std::swap(minVal, maxVal);
            std::uniform_int_distribution<int> dist(minVal, maxVal);
            return dist(rng);
        }

        void syncFrame() {
            auto now = std::chrono::steady_clock::now();
            auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(now - lastFrameTime).count();
            long long duration = 1000 / targetFps;
            if (elapsed < duration) std::this_thread::sleep_for(std::chrono::milliseconds(duration - elapsed));
            lastFrameTime = std::chrono::steady_clock::now();
        }

        void destroy(std::shared_ptr<BaseEntity> ent) {
            if (ent) ent->active = false;
        }
    };
} // namespace GameRuntime

)RAW";

    // Global engine instance
    ss << "GameRuntime::Engine engine("
       << program.config.width << ", "
       << program.config.height << ", "
       << program.config.fps << ", \""
       << program.config.title << "\");\n\n";

    // Entity Struct Definitions
    for (const auto& entity : program.entities) {
        ss << "struct Entity_" << entity->name << " : public GameRuntime::BaseEntity {\n";
        for (const auto& field : entity->fields) {
            bool isBase = (field.name == "x" || field.name == "y" || field.name == "vx" || field.name == "vy" ||
                           field.name == "symbol" || field.name == "color");
            if (!isBase) {
                bool isStr = false;
                if (field.defaultValue) {
                    if (auto lit = dynamic_cast<LiteralExpr*>(field.defaultValue.get())) {
                        if (lit->kind == LiteralExpr::Kind::String) isStr = true;
                    }
                }
                if (isStr) ss << "    std::string " << field.name << " = ";
                else ss << "    double " << field.name << " = ";
                if (field.defaultValue) transpileExpression(*field.defaultValue, ss);
                else ss << "0.0";
                ss << ";\n";
            }
        }
        ss << "    Entity_" << entity->name << "() {\n";
        ss << "        type = \"" << entity->name << "\";\n";
        for (const auto& field : entity->fields) {
            bool isBase = (field.name == "x" || field.name == "y" || field.name == "vx" || field.name == "vy" ||
                           field.name == "symbol" || field.name == "color");
            if (isBase && field.defaultValue) {
                ss << "        " << field.name << " = ";
                transpileExpression(*field.defaultValue, ss);
                ss << ";\n";
            }
        }
        ss << "    }\n";
        ss << "};\n\n";
    }

    // Global entity lists
    for (const auto& entity : program.entities) {
        ss << "std::vector<std::shared_ptr<Entity_" << entity->name << ">> entities_" << entity->name << ";\n";
    }
    ss << "\n";

    // Spawn helper template
    for (const auto& entity : program.entities) {
        ss << "std::shared_ptr<Entity_" << entity->name << "> spawn_" << entity->name << "() {\n";
        ss << "    auto e = std::make_shared<Entity_" << entity->name << ">();\n";
        ss << "    e->id = engine.nextId++;\n";
        ss << "    entities_" << entity->name << ".push_back(e);\n";
        ss << "    engine.entities.push_back(e);\n";
        ss << "    return e;\n";
        ss << "}\n\n";
    }

    // Global variables
    for (const auto& g : program.globals) {
        ss << "GameRuntime::Value " << g->name << " = ";
        if (g->initializer) {
            transpileExpression(*g->initializer, ss);
        } else {
            ss << "0.0";
        }
        ss << ";\n";
    }
    ss << "\n";

    // Helper functions
    ss << "inline bool key(const std::string& k) { return engine.isKeyDown(k); }\n";
    ss << "inline bool key_down(const std::string& k) { return engine.isKeyDown(k); }\n";
    ss << "inline bool key_pressed(const std::string& k) { return engine.isKeyPressed(k); }\n";
    ss << "inline void beep(int f, int d) { engine.playBeep(f, d); }\n";
    ss << "inline int random(int minVal, int maxVal) { return engine.getRandomInt(minVal, maxVal); }\n";
    ss << "inline void destroy(std::shared_ptr<GameRuntime::BaseEntity> e) { engine.destroy(e); }\n";
    ss << "inline void destroy(const GameRuntime::Value& v) { if (v.entity) engine.destroy(v.entity); }\n";
    ss << "inline int count(const std::string& type) {\n";
    ss << "    int cnt = 0;\n";
    ss << "    for (const auto& e : engine.entities) {\n";
    ss << "        if (e->active && e->type == type) cnt++;\n";
    ss << "    }\n";
    ss << "    return cnt;\n";
    ss << "}\n\n";

    // RPG Map helpers
    ss << "inline void tile(const GameRuntime::Value& x, const GameRuntime::Value& y, const GameRuntime::Value& ch, const GameRuntime::Value& col = \"white\", const GameRuntime::Value& solid = 0.0) {\n";
    ss << "    char c = ch.str.empty() ? ' ' : ch.str[0];\n";
    ss << "    engine.setTile((int)x.num, (int)y.num, c, GameRuntime::parseColor(col.str), solid.num != 0.0);\n";
    ss << "}\n";
    ss << "inline GameRuntime::Value tile_solid(const GameRuntime::Value& x, const GameRuntime::Value& y) {\n";
    ss << "    return GameRuntime::Value(engine.isTileSolid((int)x.num, (int)y.num) ? 1.0 : 0.0);\n";
    ss << "}\n";
    ss << "inline GameRuntime::Value tile_at(const GameRuntime::Value& x, const GameRuntime::Value& y) {\n";
    ss << "    return GameRuntime::Value(std::string(1, engine.getTileChar((int)x.num, (int)y.num)));\n";
    ss << "}\n";
    ss << "inline void map_box(const GameRuntime::Value& x, const GameRuntime::Value& y, const GameRuntime::Value& w, const GameRuntime::Value& h, const GameRuntime::Value& ch = \"#\", const GameRuntime::Value& col = \"gray\", const GameRuntime::Value& solid = 1.0) {\n";
    ss << "    char c = ch.str.empty() ? '#' : ch.str[0];\n";
    ss << "    engine.fillMapBox((int)x.num, (int)y.num, (int)w.num, (int)h.num, c, GameRuntime::parseColor(col.str), solid.num != 0.0);\n";
    ss << "}\n";
    ss << "inline void map_row(const GameRuntime::Value& x, const GameRuntime::Value& y, const GameRuntime::Value& row, const GameRuntime::Value& col = \"white\", const GameRuntime::Value& solid = 0.0) {\n";
    ss << "    engine.setMapRow((int)x.num, (int)y.num, row.str, GameRuntime::parseColor(col.str), solid.num != 0.0);\n";
    ss << "}\n";
    ss << "inline void camera(const GameRuntime::Value& cx, const GameRuntime::Value& cy) {\n";
    ss << "    engine.setCamera((int)cx.num, (int)cy.num);\n";
    ss << "}\n";
    ss << "inline void msg(const GameRuntime::Value& m, const GameRuntime::Value& col = \"yellow\") {\n";
    ss << "    engine.setMessage(m.str.empty() ? std::to_string((int)m.num) : m.str, GameRuntime::parseColor(col.str));\n";
    ss << "}\n";
    ss << "inline void dialog(const GameRuntime::Value& m, const GameRuntime::Value& col = \"yellow\") {\n";
    ss << "    msg(m, col);\n";
    ss << "}\n\n";

    // Functions
    for (const auto& fn : program.functions) {
        ss << "GameRuntime::Value fn_" << fn->name << "(";
        for (size_t i = 0; i < fn->params.size(); ++i) {
            ss << "GameRuntime::Value " << fn->params[i] << (i + 1 < fn->params.size() ? ", " : "");
        }
        ss << ") {\n";
        if (fn->body) {
            for (const auto& stmt : fn->body->statements) {
                transpileStatement(*stmt, ss, 1);
            }
        }
        ss << "    return 0.0;\n}\n\n";
    }

    // Function fallback stubs for undefined calls
    std::unordered_set<std::string> declaredFns;
    for (const auto& fn : program.functions) declaredFns.insert(fn->name);
    declaredFns.insert("key"); declaredFns.insert("key_down"); declaredFns.insert("key_pressed");
    declaredFns.insert("beep"); declaredFns.insert("random"); declaredFns.insert("destroy");
    declaredFns.insert("count");
    declaredFns.insert("tile"); declaredFns.insert("tile_solid"); declaredFns.insert("tile_at");
    declaredFns.insert("map_box"); declaredFns.insert("map_row"); declaredFns.insert("camera");
    declaredFns.insert("msg"); declaredFns.insert("dialog");

    for (const auto& call : calledFunctions) {
        if (declaredFns.find(call) == declaredFns.end()) {
            ss << "template<typename... Args> inline GameRuntime::Value fn_" << call << "(Args&&...) { return 0.0; }\n";
        }
    }
    ss << "\n";

    // Init function
    ss << "void game_init() {\n";
    if (program.initBlock) {
        for (const auto& stmt : program.initBlock->statements) {
            transpileStatement(*stmt, ss, 1);
        }
    }
    ss << "}\n\n";

    // Update function
    ss << "void game_update() {\n";
    ss << "    for (auto& e : engine.entities) {\n";
    ss << "        if (!e->active) continue;\n";
    ss << "        e->x += e->vx;\n";
    ss << "        e->y += e->vy;\n";
    ss << "        if (e->type == \"Bullet\" && (e->y < 1 || e->y >= engine.height - 1)) e->active = false;\n";
    ss << "    }\n";
    if (program.updateBlock) {
        for (const auto& stmt : program.updateBlock->statements) {
            transpileStatement(*stmt, ss, 1);
        }
    }
    ss << "}\n\n";

    // Collisions
    ss << "void game_collisions() {\n";
    for (const auto& ch : program.collisionHandlers) {
        ss << "    // Collision: " << ch->entityA << " vs " << ch->entityB << "\n";
        ss << "    for (auto& " << ch->varA << "_ptr : entities_" << ch->entityA << ") {\n";
        ss << "        if (!" << ch->varA << "_ptr->active) continue;\n";
        ss << "        for (auto& " << ch->varB << "_ptr : entities_" << ch->entityB << ") {\n";
        ss << "            if (!" << ch->varB << "_ptr->active) continue;\n";
        ss << "            if (std::round(" << ch->varA << "_ptr->x) == std::round(" << ch->varB << "_ptr->x) &&\n";
        ss << "                std::round(" << ch->varA << "_ptr->y) == std::round(" << ch->varB << "_ptr->y)) {\n";
        ss << "                GameRuntime::Value " << ch->varA << "(" << ch->varA << "_ptr);\n";
        ss << "                GameRuntime::Value " << ch->varB << "(" << ch->varB << "_ptr);\n";
        if (ch->body) {
            for (const auto& stmt : ch->body->statements) {
                transpileStatement(*stmt, ss, 4);
            }
        }
        ss << "            }\n";
        ss << "        }\n";
        ss << "    }\n";
    }
    ss << "}\n\n";

    // Render function
    ss << "void game_render() {\n";
    ss << "    engine.clear();\n";
    ss << "    for (int sy = 1; sy < engine.height - 1; ++sy) {\n";
    ss << "        int my = sy + engine.cameraY;\n";
    ss << "        if (my < 0 || my >= engine.mapHeight) continue;\n";
    ss << "        for (int sx = 1; sx < engine.width - 1; ++sx) {\n";
    ss << "            int mx = sx + engine.cameraX;\n";
    ss << "            if (mx < 0 || mx >= engine.mapWidth) continue;\n";
    ss << "            const auto& t = engine.tiles[my * engine.mapWidth + mx];\n";
    ss << "            if (t.ch != ' ' && t.ch != '\\0') engine.setPixel(sx, sy, t.ch, t.color);\n";
    ss << "        }\n";
    ss << "    }\n";
    ss << "    engine.drawBox(0, 0, engine.width, engine.height, GameRuntime::Color::Blue);\n";
    ss << "    engine.drawText(2, 0, \" " << program.config.title << " \", GameRuntime::Color::Cyan);\n";
    bool hasScore = false;
    bool hasLives = false;
    bool hasHp = false;
    bool hasGold = false;
    for (const auto& g : program.globals) {
        if (g->name == "score") hasScore = true;
        if (g->name == "lives") hasLives = true;
        if (g->name == "hp") hasHp = true;
        if (g->name == "gold") hasGold = true;
    }
    if (hasScore) {
        ss << "    engine.drawText(engine.width - 16, 0, \"Score: \" + std::to_string((int)score), GameRuntime::Color::Yellow);\n";
    }
    if (hasLives) {
        ss << "    engine.drawText(2, engine.height - 1, \"Lives: \" + std::to_string((int)lives), GameRuntime::Color::Green);\n";
    }
    if (hasHp) {
        ss << "    engine.drawText(" << (hasLives ? 14 : 2) << ", engine.height - 1, \"HP: \" + std::to_string((int)hp), GameRuntime::Color::Red);\n";
    }
    if (hasGold) {
        ss << "    engine.drawText(26, engine.height - 1, \"Ouro: \" + std::to_string((int)gold), GameRuntime::Color::Yellow);\n";
    }

    // Draw entities (with camera offset)
    for (const auto& entity : program.entities) {
        ss << "    for (auto& e : entities_" << entity->name << ") {\n";
        ss << "        if (e->active) {\n";
        ss << "            int ex = (int)std::round(e->x) - engine.cameraX;\n";
        ss << "            int ey = (int)std::round(e->y) - engine.cameraY;\n";
        ss << "            if (ex > 0 && ex < engine.width - 1 && ey > 0 && ey < engine.height - 1) {\n";
        ss << "                engine.setPixel(ex, ey, e->symbol.empty() ? '?' : e->symbol[0], GameRuntime::parseColor(e->color));\n";
        ss << "            }\n";
        ss << "        }\n";
        ss << "    }\n";
    }

    if (program.renderBlock) {
        for (const auto& stmt : program.renderBlock->statements) {
            transpileStatement(*stmt, ss, 1);
        }
    }

    // RPG Dialogue banner
    ss << "    if (!engine.currentMessage.empty()) {\n";
    ss << "        std::string msgBar = \"[ \" + engine.currentMessage + \" ]\";\n";
    ss << "        int msgX = std::max(2, (engine.width - (int)msgBar.length()) / 2);\n";
    ss << "        engine.drawText(msgX, engine.height - 2, msgBar, engine.messageColor);\n";
    ss << "    }\n";

    ss << "    engine.drawText(engine.width - 15, engine.height - 1, \"[ESC/Q: Sair]\", GameRuntime::Color::Default);\n";
    ss << "    engine.present();\n";
    ss << "}\n\n";

    // Main entry point
    ss << "int main() {\n";
    ss << "    engine.initTerminal();\n";
    ss << "    try { game_init(); } catch (...) {}\n";
    ss << "    while (!engine.exitRequested) {\n";
    ss << "        engine.pollInput();\n";
    ss << "        try { game_update(); } catch (...) {}\n";
    ss << "        try { game_collisions(); } catch (...) {}\n";
    ss << "        try { game_render(); } catch (...) {}\n";
    ss << "        engine.syncFrame();\n";
    ss << "    }\n";
    ss << "    engine.resetTerminal();\n";
    ss << "    return 0;\n";
    ss << "}\n";

    return ss.str();
}

void Transpiler::transpileStatement(const Stmt& stmt, std::ostringstream& ss, int indent) {
    if (auto varDecl = dynamic_cast<const VarDeclStmt*>(&stmt)) {
        emitIndent(ss, indent);
        ss << "auto " << varDecl->name << " = ";
        if (varDecl->initializer) transpileExpression(*varDecl->initializer, ss);
        else ss << "0.0";
        ss << ";\n";
    } else if (auto ifStmt = dynamic_cast<const IfStmt*>(&stmt)) {
        emitIndent(ss, indent);
        ss << "if (";
        transpileExpression(*ifStmt->condition, ss);
        ss << ") {\n";
        if (ifStmt->thenBranch) transpileStatement(*ifStmt->thenBranch, ss, indent + 1);
        emitIndent(ss, indent);
        ss << "}";
        if (ifStmt->elseBranch) {
            ss << " else {\n";
            transpileStatement(*ifStmt->elseBranch, ss, indent + 1);
            emitIndent(ss, indent);
            ss << "}";
        }
        ss << "\n";
    } else if (auto whileStmt = dynamic_cast<const WhileStmt*>(&stmt)) {
        emitIndent(ss, indent);
        ss << "while (";
        transpileExpression(*whileStmt->condition, ss);
        ss << ") {\n";
        if (whileStmt->body) transpileStatement(*whileStmt->body, ss, indent + 1);
        emitIndent(ss, indent);
        ss << "}\n";
    } else if (auto blockStmt = dynamic_cast<const BlockStmt*>(&stmt)) {
        for (const auto& s : blockStmt->statements) transpileStatement(*s, ss, indent);
    } else if (auto returnStmt = dynamic_cast<const ReturnStmt*>(&stmt)) {
        emitIndent(ss, indent);
        if (returnStmt->value) {
            ss << "return ";
            transpileExpression(*returnStmt->value, ss);
            ss << ";\n";
        } else {
            ss << "return;\n";
        }
    } else if (auto destroyStmt = dynamic_cast<const DestroyStmt*>(&stmt)) {
        emitIndent(ss, indent);
        ss << "destroy(";
        transpileExpression(*destroyStmt->target, ss);
        ss << ");\n";
    } else if (auto exprStmt = dynamic_cast<const ExprStmt*>(&stmt)) {
        emitIndent(ss, indent);
        transpileExpression(*exprStmt->expr, ss);
        ss << ";\n";
    }
}

void Transpiler::transpileExpression(const Expr& expr, std::ostringstream& ss) {
    if (auto lit = dynamic_cast<const LiteralExpr*>(&expr)) {
        switch (lit->kind) {
            case LiteralExpr::Kind::Number: ss << lit->numberVal; break;
            case LiteralExpr::Kind::String: ss << "\"" << lit->stringVal << "\""; break;
            case LiteralExpr::Kind::Boolean: ss << (lit->boolVal ? "true" : "false"); break;
            case LiteralExpr::Kind::Null: ss << "nullptr"; break;
        }
    } else if (auto varExpr = dynamic_cast<const VariableExpr*>(&expr)) {
        ss << varExpr->name;
    } else if (auto bin = dynamic_cast<const BinaryExpr*>(&expr)) {
        ss << "(";
        transpileExpression(*bin->left, ss);
        ss << " " << Token::tokenTypeName(bin->op) << " ";
        transpileExpression(*bin->right, ss);
        ss << ")";
    } else if (auto un = dynamic_cast<const UnaryExpr*>(&expr)) {
        ss << Token::tokenTypeName(un->op);
        transpileExpression(*un->right, ss);
    } else if (auto asgn = dynamic_cast<const AssignExpr*>(&expr)) {
        ss << asgn->name << " " << Token::tokenTypeName(asgn->op) << " ";
        transpileExpression(*asgn->value, ss);
    } else if (auto mem = dynamic_cast<const MemberAccessExpr*>(&expr)) {
        transpileExpression(*mem->object, ss);
        ss << "->" << mem->member;
    } else if (auto memAsgn = dynamic_cast<const MemberAssignExpr*>(&expr)) {
        transpileExpression(*memAsgn->object, ss);
        ss << "->" << memAsgn->member << " " << Token::tokenTypeName(memAsgn->op) << " ";
        transpileExpression(*memAsgn->value, ss);
    } else if (auto call = dynamic_cast<const CallExpr*>(&expr)) {
        if (call->callee == "key" || call->callee == "key_down" || call->callee == "key_pressed" ||
            call->callee == "beep" || call->callee == "random" || call->callee == "destroy" ||
            call->callee == "count" || call->callee == "tile" || call->callee == "tile_solid" ||
            call->callee == "tile_at" || call->callee == "map_box" || call->callee == "map_row" ||
            call->callee == "camera" || call->callee == "msg" || call->callee == "dialog") {
            ss << call->callee << "(";
        } else {
            ss << "fn_" << call->callee << "(";
        }
        for (size_t i = 0; i < call->arguments.size(); ++i) {
            transpileExpression(*call->arguments[i], ss);
            if (i + 1 < call->arguments.size()) ss << ", ";
        }
        ss << ")";
    } else if (auto spawn = dynamic_cast<const SpawnExpr*>(&expr)) {
        ss << "spawn_" << spawn->entityType << "()";
    }
}

} // namespace GameLang
